Add support for thumbnails in AASXSerializer / AASXDeserializer
eclipse-aas4j/aas4j pull request #165
Opened 2023-08-31 14:55 UTC by fvolz

The AASXSerializer/Deserializer ignored thumbnails when loading or saving files in the AASX.
The thumbnails are now properly processed as files.

2023-09-01 06:44 UTC, mjacoby commented on dataformat-aasx/src/main/java/org/eclipse/digitaltwin/aas4j/v3/dataformat/aasx/AASXDeserializer.java
> +            paths.add(aas.getAssetInformation().getDefaultThumbnail().getPath());
Should probably add null checks for `aas.getAssetInformation()`, `getAssetInformation().getDefaultThumbnail()`, and `aas.getAssetInformation().getDefaultThumbnail().getPath()`.

2023-09-01 06:45 UTC, mjacoby commented on dataformat-aasx/src/main/java/org/eclipse/digitaltwin/aas4j/v3/dataformat/aasx/AASXSerializer.java
> +            String filePath = AASXUtils.getPathFromURL(aas.getAssetInformation().getDefaultThumbnail().getPath());
Should probably add null checks for `aas.getAssetInformation()`, `getAssetInformation().getDefaultThumbnail()`, and `aas.getAssetInformation().getDefaultThumbnail().getPath()`.

2023-09-22 11:24 UTC, FrankSchnicke requested changes
Thank you very much for your contribution. Please see my separate comments for the review.

2023-09-22 11:24 UTC, FrankSchnicke commented on dataformat-aasx/src/main/java/org/eclipse/digitaltwin/aas4j/v3/dataformat/aasx/AASXSerializer.java
> +            try {
This part is copy & paste of the logic in the Submodel processing. Please extract it in a common function

2023-09-22 11:24 UTC, FrankSchnicke commented on dataformat-aasx/src/main/java/org/eclipse/digitaltwin/aas4j/v3/dataformat/aasx/AASXSerializer.java
> +        for (AssetAdministrationShell aas : environment.getAssetAdministrationShells()) {
I think this whole logic could be drastically simplified by using a stream, using the predicate given in l. 132 as filter and then applying the rest of the logic via forEach

2023-09-22 11:24 UTC, FrankSchnicke commented on dataformat-aasx/src/main/java/org/eclipse/digitaltwin/aas4j/v3/dataformat/aasx/AASXDeserializer.java
> +            if(information == null || information.getDefaultThumbnail() == null || information.getDefaultThumbnail().getPath() == null) {
See the other comment above. I think filtering via a stream and then using forEach is a better pattern in contrast to having a _continue_ within a loop

2023-10-05 07:41 UTC, FrankSchnicke approved these changes

2023-10-05 07:42 UTC, merged