Update to rc02 smlist tests
eclipse-aas4j/aas4j pull request #22
Opened 2022-08-17 16:45 UTC by sebbader-sap

This PR introduces SubmodelElementLists into the AASFull test elements.

2022-08-17 16:47 UTC, sebbader-sap commented
This PR is related to #13

2022-08-18 13:01 UTC, mjacoby requested changes
Changes in AAS full example introduced inconcsistencies that need to be fixed.

2022-08-18 13:01 UTC, mjacoby commented on dataformat-json/src/test/java/org/eclipse/aas4j/v3/dataformat/json/JsonReferableDeserializerTest.java
> +import org.eclipse.aas4j.v3.model.*;
Avoid using wildcard imports as this is typically considered bad style (see e.g. https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad)

2022-08-18 13:01 UTC, mjacoby commented on dataformat-core/src/test/java/org/eclipse/aas4j/v3/dataformat/core/AASFull.java
>                          .idShort("ExampleSubmodelCollectionOrdered")
Changing element type (here from `SubmodelElementCollection` to `SubmodelElementList`) requires also changing other places this type is used, e.g. when building a Reference to this element like done at https://github.com/eclipse-digitaltwin/aas4j/blob/9e50db894089ec938f457c9d2b5acc6e59e7f082/dataformat-core/src/test/java/org/eclipse/aas4j/v3/dataformat/core/AASFull.java#L980

The whole file needs to be checked for consistency whenever changing an element type. This also applies to all other similar changes in this file.

2022-08-18 13:01 UTC, mjacoby commented on dataformat-core/src/test/java/org/eclipse/aas4j/v3/dataformat/core/AASFull.java
> +                .submodelElements(new DefaultSubmodelElementList.Builder()
Seems like all instances of `SubmodelElementList` in this file now have `orderRelevant=true` which means we have no test case with `orderRelevant=false`.
We should have such a case - either by changing one of the existing elements or by adding a new one.

2022-08-18 13:01 UTC, mjacoby commented on dataformat-json/src/test/java/org/eclipse/aas4j/v3/dataformat/json/JsonReferableDeserializerTest.java
> +    public void testReadSubmodelElementColelction() throws IOException, DeserializationException {
typo in method name, `Colelction` should be `Collection`

2022-08-18 13:01 UTC, mjacoby commented on dataformat-json/src/test/java/org/eclipse/aas4j/v3/dataformat/json/JsonReferableSerializerTest.java
> +    public void testSerializeSubmodelelementList() throws IOException, SerializationException, JSONException {
Don't replace test method! Keep old test and add new one.

2022-08-18 13:01 UTC, mjacoby commented on dataformat-json/src/test/resources/test_demo_full_example.json
> +                            "type": "GlobalReference",
`type` is defined twice, here and in L281. Is this the official way to serialize dataSpecificaitions? Seems redundant

2022-08-18 13:01 UTC, mjacoby commented on dataformat-json/src/test/resources/test_demo_full_example.json
> +                    "modelType": "SubmodelElementList",
Changing element type also requires to update related elements in whole document, e.g. references such as https://github.com/eclipse-digitaltwin/aas4j/blob/9e50db894089ec938f457c9d2b5acc6e59e7f082/dataformat-json/src/test/resources/test_demo_full_example.json#L715

2022-09-09 15:50 UTC, sebbader commented on dataformat-json/src/test/resources/test_demo_full_example.json
> +                            "type": "GlobalReference",
It's somehow redundant - but yes, that's the official pattern for V3.0RC02.

2022-09-09 15:57 UTC, sebbader commented on dataformat-core/src/test/java/org/eclipse/aas4j/v3/dataformat/core/AASFull.java
> +                .submodelElements(new DefaultSubmodelElementList.Builder()
Valid point, just changed this with todays's commits.

2022-09-09 15:57 UTC, sebbader commented on dataformat-json/src/test/java/org/eclipse/aas4j/v3/dataformat/json/JsonReferableDeserializerTest.java
> +    public void testReadSubmodelElementColelction() throws IOException, DeserializationException {
done

2022-09-09 15:58 UTC, sebbader commented on dataformat-json/src/test/java/org/eclipse/aas4j/v3/dataformat/json/JsonReferableSerializerTest.java
> +    public void testSerializeSubmodelelementList() throws IOException, SerializationException, JSONException {
added a SMC UnitTest again

2022-09-09 15:58 UTC, sebbader commented
@mjacoby please check the PR again, I hope I have regarded every point.

2022-09-14 11:51 UTC, mjacoby commented on dataformat-json/src/test/java/org/eclipse/aas4j/v3/dataformat/json/JsonReferableDeserializerTest.java
> +import org.eclipse.aas4j.v3.model.*;
Still unresolved...looks like it was fixed with one commit and then re-introduced in later commit.

2022-09-14 12:47 UTC, sebbader commented on dataformat-json/src/test/java/org/eclipse/aas4j/v3/dataformat/json/JsonReferableDeserializerTest.java
> +import org.eclipse.aas4j.v3.model.*;
Damn. My Intelij replaces the imports by it's own if a certain number of class imports happened. Need to deactivate this feature.

2022-09-14 12:58 UTC, sebbader commented on dataformat-json/src/test/java/org/eclipse/aas4j/v3/dataformat/json/JsonReferableDeserializerTest.java
> +import org.eclipse.aas4j.v3.model.*;
@mjacoby please check again.

2022-09-21 11:43 UTC, mjacoby commented
**Current stauts**

Problems with handling of default values, e.g. for 'SubmodelElementList.orderRelevant'. After discussion with @sebbader-sap we decided that this be solved on model level, i.e. default values should be set in constructors of default implementation classes. This requires updating the generator but also the RDF file to contain information about default values (which it currently does not). Not sure if RDF file is currently auto-generated by another tool, but if so, this might require to update this tool too. 

@sebbader-sap is working on this issue
@mjacoby will review changes once this is done

2022-09-28 09:28 UTC, sebbader-sap commented
@mjacoby please comment here after we have finished https://github.com/eclipse-digitaltwin/aas4j-model-generator/issues/6 ?

2022-09-28 09:28 UTC, sebbader-sap commented
Then I will resolve the conflicts and we can merge the PR.

2022-10-28 16:08 UTC, merged